accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns=[
    url(r'^signup/$',views.signup_view,name='signup'),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.logout_view,name='logout')
]

articles/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views
from django.urls import re_path

app_name = 'articles'

urlpatterns=[
    url(r'^$',views.articles_home,name='articles_home'),
    url(r'^news',views.news,name='news'),
    url(r'^transfers',views.transfers,name='transfers'),
    url(r'^analysis',views.analysis,name='analysis'),
    url(r'^create/$',views.create,name='create'),
    re_path('(?P<slug>[\w-]+)/$', views.article_detail,name='detail')
]

football_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from football_blog import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$',views.home,name='home_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^about',views.about,name='about'),
    url(r'^joinus',views.join,name='joinus'),
    url(r'^articles/',include('articles.urls')),
    url(r'^accounts/',include('accounts.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
TYPE_CHOICES = (
    ('ANALYSIS', 'Analysis'),
    ('NEWS', 'News'),
    ('TRANSFERS', 'Transfers'),
)

class Article(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100,default='No Description Available')
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True) # automatically put datestamp
    type = models.CharField(max_length=10,choices=TYPE_CHOICES)
    thumb = models.ImageField(upload_to='thumbnail_pics',blank=True)
    author = models.ForeignKey(User,on_delete = models.CASCADE,default=None)

def __str__(self):
    return self.title

articles/forms.py
from django import forms
from .models import Article


class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','slug','description','body','type','thumb']
        widgets = { 'title':forms.TextInput(attrs={'class': 'form-control'}),
                    'slug':forms.TextInput(attrs={'class': 'form-control'}),
                    'description':forms.Textarea(attrs={'class': 'form-control'}),
                    'body':forms.Textarea(attrs={'class': 'form-control'}),
                    'type':forms.Select(attrs={'class': 'form-control'})
                }

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.

def signup_view(request):
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            #log the user in
            return redirect("home_page")
    else:
        form = UserCreationForm()
        return render(request,"accounts/signup.html",{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request,user)
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("home_page")
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home_page')

articles/views.py
from django.shortcuts import render,redirect
from articles.models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def articles_home(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'articles/articles_home.html',{'articles':articles})

def news(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'articles/news.html',{'articles':articles})

def transfers(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'articles/transfers.html',{'articles':articles})

def analysis(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'articles/analysis.html',{'articles':articles})

def article_detail(request,slug):
    articleslug = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':articleslug})

@login_required(login_url = '/accounts/login')
def create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()

            return redirect("home_page")
    else:
        form = forms.CreateArticle
        return render(request,'articles/article_create.html',{'form':form})

football_blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles.models import Article


def home(request):
    articles = Article.objects.all().order_by('-date')
    return render(request,'homepage.html',{'articles':articles})

def about(request):
    return render(request,'about.html')

def join(request):
    return render(request,'join_us.html')

def submit(request):
    return render(request,'render.html')

templates/about.html
{% extends "base.html" %}
{% load static %}
  {% block body_block %}
  <style>
    #mission{
      font-size:1.3em;
    }
  </style>
  <title>About</title>
<h1 class="pt-5">OUR MISSION</h1>
   <hr color="grey">
<p id='mission'>At Turf Football, we believe in producing the best footballing content for our readers. Our aim is to give you a different perspective on football and cover some of the hidden stories that often go unnoticed. We strive to bring about different opinions from different parts of the world and we dream of creating an impact on society through football.</p>


   <h1 class="pt-5">FOUNDERS</h1>
   <hr color="grey">
      <h2 class="pt-3">Vansh Ambashta</h2>
      <h5>Chief Editor / Content Lead</h5>
      <div class="row pt-2 mb-5">
      <div class="col-6">
        <div class="text-muted">
        <br>B.Tech, Mechanical Engineering</br>
        <br>Motilal Nehru National Institute of Technology, Allahabad </br>
      </div>
      </div>
      <div class="col-6"><img src="{% static 'images/vansh.jpeg' %}" alt="teri photo" style="width:300px;height:300px"></div>
      </div>

      <h2 class="pt-1">Chaitanya Shashwat</h2>
      <h5>Administrator / Marketing Lead</h5>
      <div class="row pt-2 mb-5">
      <div class="col-6">
        <div class="text-muted">
        <br>B.Tech, Civil Engineering</br>
        <br>National Institute of Technology Surathkal </br>
      </div>
      </div>
      <div class="col-6"><img src="{% static 'images/chetu.jpeg' %}" alt="meri photo" style="width:300px;height:300px"></div>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<h1 class="pt-5"><img src="{%static "images/logo_3.png"%}" style="width:40px;height:40px" alt="turf"> Login</h1>



<hr color="grey">
<h4>Want to write for us?</h4>
<br>
<h6 style padding-top:3%>Visit this<a href="{%url 'joinus'%}"> page</a> to enquire.</h6>
<br>
<form class="site-form" action={% url 'accounts:login' %} method="post">
  {% csrf_token %}
    {{form.as_p}}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" name="" value="Login">
</form>
<br>
<br>
<br>
<br>
{% endblock %}

templates/accounts/signup.html
{%extends 'base.html'%}
{% block body_block %}
  <h1>Sign Up</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
      {{form}}
    <input type="submit" name="" value="Signup">
  </form>


{% endblock %}

templates/articles/analysis.html
{% extends "base.html" %}
  {% block body_block %}
  <style>
     a { color: #000000; }
     a:hover{color:#000000; text-decoration:none;}
  </style>
    <title>Analysis</title>
    <h1 class="mt-5">ANALYSIS</h1>
    <hr color="grey">
    {% for article in articles %}
    {% if article.type == 'ANALYSIS' %}
    <div class="card mb-3">
      <span title="{{article.title}}">
      <a href="{%url 'articles:detail' slug=article.slug %}">
      <div class="card-body">
        <h3 class="card-title">{{article.title}}</h3>
      <div class="card-subtitle mb-1 text-muted">
        <p>{{article.type}}</p>
        <p>By {{article.author}}</p>
        <p>{{article.date}}</p>
      </div>
      <div>
      <img class="card-img-top" src="{{article.thumb.url}}" alt="NO IMAGE FOUND">
    </div>
      <p class="card-text pt-2">{{article.description}}</p>
    </div>
    </a>
    </span>
  </div>
    {% endif %}
    {% endfor %}
  {% endblock %}

templates/articles/article_create.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
  <title>Write</title>
  <h1 class="pt-5">WRITE ARTICLE</h1>
  <hr color="grey">
  <form action="{% url 'articles:create' %}" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class='btn btn-primary mb-5'>Create</button>
  </form>
  <script type="text/javascript" src="{%static 'js/slugify.js'%}"></script>
{% endblock %}

templates/articles/article_detail.html
{% extends "base.html" %}
  {% block body_block %}
    <title>{{article.title}}</title>
    <h2 class="pt-5">{{article.title}}</h2>
    <div class="row">
    <div class="col-lg-6 col-md-6 col-12">
    <p>By {{article.author}}</p>
    <p>{{article.type}}</p>
    <p>{{article.date}}</p>
    <p>{{article.body|linebreaks}}</p>
    </div>
    <div class="col-lg-4 col-md-4 col-12 pt-4">
      <img src="{{article.thumb.url}}" alt="NO IMAGE FOUND" height="400px" width="600px">
    </div>
    </div>
       <button id="shareButton" onclick="share(this)">
        Share
        <div class="container">
          <div class="addthis_inline_share_toolbox"></div>
          
          <!--for old users of AddThis-->
          <div class="addthis_sharing_toolbox"></div>
        </div>
      </button>
    </div>
    </div>


  {% endblock %}

templates/articles/articles_home.html
{% extends "base.html" %}
  {% block body_block %}
  <style>
     a { color: #000000; }
     a:hover{color:#000000; text-decoration:none;}
  </style>
    <title>Articles</title>
    <h1 class="mt-5">ARTICLES</h1>
    <hr color="grey">
    {% for article in articles %}
    <div class="card mb-3">
      <span title="{{article.title}}">
      <a href="{%url 'articles:detail' slug=article.slug %}">
      <div class="card-body">
        <h3 class="card-title">{{article.title}}</h3>
      <div class="card-subtitle mb-1 text-muted">
        <p>{{article.type}}</p>
        <p>By {{article.author}}</p>
        <p>{{article.date}}</p>
      </div>
      <div>
      <img class="card-img-top" src="{{article.thumb.url}}" alt="NO IMAGE FOUND">
    </div>
      <p class="card-text pt-2">{{article.description}}</p>
    </div>
    </a>
    </span>
  </div>
    {% endfor %}
  {% endblock %}

templates/articles/news.html
{% extends "base.html" %}
  {% block body_block %}
  <style>
     a { color: #000000; }
     a:hover{color:#000000; text-decoration:none;}
  </style>
    <title>News</title>
    <h1 class="mt-5">NEWS</h1>
    <hr color="grey">
    {% for article in articles %}
    {% if article.type == 'NEWS' %}
    <div class="card mb-3">
      <span title="{{article.title}}">
      <a href="{%url 'articles:detail' slug=article.slug %}">
      <div class="card-body">
        <h3 class="card-title">{{article.title}}</h3>
      <div class="card-subtitle mb-1 text-muted">
        <p>{{article.type}}</p>
        <p>By {{article.author}}</p>
        <p>{{article.date}}</p>
      </div>
      <div>
      <img class="card-img-top" src="{{article.thumb.url}}" alt="NO IMAGE FOUND">
    </div>
      <p class="card-text pt-2">{{article.description}}</p>
    </div>
    </a>
    </span>
  </div>

    {% endif %}
    {% endfor %}
  {% endblock %}

templates/articles/transfers.html
{% extends "base.html" %}
  {% block body_block %}
  <style>
     a { color: #000000; }
     a:hover{color:#000000; text-decoration: none;}
  </style>
    <title>Transfers</title>
    <h1 class="mt-5">TRANSFER & RUMOURS</h1>
    <hr color="grey">
    {% for article in articles %}
    {% if article.type == 'TRANSFERS' %}
    <div class="card mb-3">
      <span title="{{article.title}}">
      <a href="{%url 'articles:detail' slug=article.slug %}">
        <div class="card-body">
          <h3 class="card-title">{{article.title}}</h3>
        <div class="card-subtitle mb-1 text-muted">
          <p>{{article.type}}</p>
          <p>By {{article.author}}</p>
          <p>{{article.date}}</p>
        </div>
        <div>
        <img class="card-img-top" src="{{article.thumb.url}}" alt="NO IMAGE FOUND">
      </div>
        <p class="card-text pt-2">{{article.description}}</p>
      </div>
    </a>
    </span>
  </div>

    {% endif %}
    {% endfor %}
  {% endblock %}

templates/base.html
<!DOCTYPE html>
{%load static%}
<html>
  <head>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' type='image/x-icon' %}">
    <meta charset="utf-8">

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js">

    <style>
footer{
  background-color: black;
  color:white;
}

nav button{
background:none;
cursor:pointer;
border:0;
color:rgba(255,255,255,.5);
}

.copyrightinfo{
font-size: 0.8em;
}

      #shareButton {
  position: fixed;
  right: 40px;
  bottom: 40px;
  width: 3.1em;
  height: 3.1em;
  font-size: 24px;
  border-radius: 50%;
  border: 0;
  outline: 0;
  background: linear-gradient(135deg, hsl(0, 100%, 30%), hsl(330, 100%, 40%));
  color: #fff;
  box-shadow: 2px 3px 8px 2px hsla(330, 100%, 40%, 0.4);
  cursor: pointer;
  transition: 0.3s;
  -webkit-tap-highlight-color: transparent;
}

#shareButton:hover {
  box-shadow: 4px 6px 16px 4px hsla(330, 100%, 40%, 0.4);
}

#shareButton i {
  position: absolute;
  transform: translate(-50%, -50%);
  left: 1.2em;
  top: 1.3em;
  transition: 0.6s;
}

#shareButton > .container {
  position: absolute;
  width: 200px;
  background: hsl(0, 40%, 95%);
  bottom: 100%;
  right: 0;
  padding: 8px;
  box-shadow: 0 0 1px 0 hsla(330, 100%, 40%, 0.4),
    2px 3px 8px 2px hsla(330, 100%, 40%, 0.4);
  margin-bottom: 16px;
  border-radius: 4px;
  opacity: 0;
  visibility: hidden;
  transition: 0.3s;
  transform: translateY(10%);
}

#shareButton > .container:hover {
  box-shadow: 0 0 1px 0 hsla(330, 100%, 40%, 0.4),
    4px 6px 16px 4px hsla(330, 100%, 40%, 0.4);
}

#shareButton.showAddThisButtons > .container {
  opacity: 1;
  visibility: visible;
  transform: translateY(0);
}

.addthis_inline_share_toolbox,
.addthis_sharing_toolbox {
  text-align: right;
}

#shareButton:after {
  content: "";
  position: absolute;
  top: 2px;
  bottom: 2px;
  left: 2px;
  right: 2px;
  border: 0 solid #fff;
  border-radius: 50%;
  border-width: 2px 0 0 2px;
  border-left-color: transparent;
  animation: loading-share-buttons 1s cubic-bezier(0.4, 0.6, 0.4, 0.6) infinite;
  animation-play-state: paused;
  opacity: 0;
  transition: 0.3s;
}

#shareButton.loading:after {
  animation-play-state: running;
  opacity: 1;
}

#shareButton i.fa-times {
  opacity: 0;
  left: 1.22em;
  transform: translate(-50%, -50%) rotate(180deg);
}

#shareButton.showAddThisButtons i.fa-share-alt {
  opacity: 0;
  transform: translate(-50%, -50%) rotate(180deg);
}

#shareButton.showAddThisButtons i.fa-times {
  opacity: 1;
  transform: translate(-50%, -50%) rotate(360deg);
}

@keyframes loading-share-buttons {
  to {
    transform: rotate(-360deg);
  }
}
    </style>


    <script>
      var AddThisJSLoaded = false; //AddThis not loaded yet
var clickedOnShare = false; //share button is not clicked

//replace with your publisher ID
//it's in your profile setting
var AddThisPubID = "ra-5ebc395e0c19dce5";
var AddThisJS =
  "//s7.addthis.com/js/300/addthis_widget.js#pubid=" + AddThisPubID;

function share(button) {
  if (navigator.share) {
    //check if Web Share API is supported by the browser
    var url = document.location.href;
    var title = document.getElementsByTagName("title")[0].innerHTML;
    var description = document
      .querySelector("meta[name=description]")
      .getAttribute("content");

    navigator.share({
      title: title,
      text: description,
      url: url
    });
  } else {
    if (!AddThisJSLoaded && !clickedOnShare) {
      //when AddThis not loaded and share button isn't clicked
      clickedOnShare = true; //share button is clicked
      showLoading(button);
      shareByAddThis(button);
    } else {
      toggleAddThisButtons(button);
    }
  }
}

function shareByAddThis(button) {
  var script = document.createElement("script");
  script.async = true;
  script.src = AddThisJS;

  script.onload = function() {
    clickedOnShare = false; //AddThis JS is loaded
    addthis.user.ready(function(data) {
      AddThisJSLoaded = true; //AddThis loaded and ready to use
      hideLoading(button);
      showAddThisButtons(button);
    });
  };

  script.onerror = function() {
    clickedOnShare = false; //AddThis JS failed to load
    hideLoading(button);
  };

  document.body.appendChild(script);
}

function showLoading(button) {
  button.classList.add("loading");
}

function hideLoading(button) {
  button.classList.remove("loading");
}

function showAddThisButtons(button) {
  button.classList.add("showAddThisButtons");
}

function toggleAddThisButtons(button) {
  button.classList.toggle("showAddThisButtons");
}
    </script>

  </head>
  <body style="background-color: #E5E5E5;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <a class="navbar-brand" href="{% url 'about' %}"><img src="{%static "images/logo_1.png"%}" style="width:35px;height:35px" alt="turf"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-item nav-link" href="{% url 'home_page' %}">Home<span class="sr-only">(current)</span></a></li>
      </li>
      <li><a class="nav-item nav-link" href="{% url 'about' %}">About</a></li>
      <li><a class="nav-item nav-link" href="{% url 'articles:articles_home' %}">Articles</a></li>
      <li><a class="nav-item nav-link" href="{% url 'articles:news' %}">News</a></li>
      <li><a class="nav-item nav-link" href="{% url 'articles:transfers' %}">Transfers</a></li>
      <li><a class="nav-item nav-link" href="{% url 'articles:analysis' %}">Analysis</a></li>
      {% if user.is_authenticated %}
        <li><a class="nav-item nav-link" href='{% url 'articles:create' %}'>Write</a></li>
        <form action="{%url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <li class="pt-2"><button type="submit">Log out</button></li>
        </form>
      {% else %}

      <li><a class="nav-item nav-link" href="{% url 'joinus' %}">Join Us</a></li>
          <li><a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log-In</a></li>
      {% endif %}
    </ul>
      </div>
    </nav>
  <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>
    <footer>
<div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
  <div class="navbar-text pull-left">

      &copy; <img src="{%static "images/logo_2.png"%}" style="width:20px;height:20px" alt="turf"> turf Football

     

  </div>
  <div class="copyrightinfo">
    <div class= "navbar-text pull-right">
        All rights reserved. The information contained on this website may not be published, broadcast, rewritten, or redistributed without prior written authority.
    </div>
  </div>

</div>
</footer>

  </body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% load static %}
  {% block body_block %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styling.css' %}">
  <title>Home</title>
    <h1 class="pt-5"><img src="{%static "images/logo_3.png"%}" style="width:50px;height:50px" alt="turf">  turf Football</h1>

    <hr color="grey">
    <div class="row mb-5">
    <div class="col-3">
      <h4 class="pt-5">Connect with Us</h4>
      <div class="vanshsocial">
      <h6>VANSH AMBASHTA</h6>
      <a class='sociallinks' href="https://www.instagram.com/ambashtavansh/" target="_blank"><p><i class="fa fa-instagram" aria-hidden="true"></i> ambashtavansh</p></a>
      <a class='sociallinks' href="https://www.facebook.com/vansh.ambashta" target="_blank"><p><i class="fa fa-facebook-square" aria-hidden="true"></i> Vansh Ambashta</p></a>
      <a class='sociallinks' href="https://twitter.com/VanshAmbashta" target="_blank"><p><i class="fa fa-twitter-square" aria-hidden="true"></i> Vansh Ambashta</p></a>
      </div>
      <div class="chetusocial">
      <h6 class="pt-4">CHAITANYA SHASHWAT</h6>
      <a class='sociallinks' href="https://www.instagram.com/i_zultan/" target="_blank"><p><i class="fa fa-instagram" aria-hidden="true"></i> i_zultan</p></a>
      <a class='sociallinks' href="https://www.facebook.com/chaitanya.shashwat.3" target="_blank"><p><i class="fa fa-facebook-square" aria-hidden="true"></i> Chaitanya Shashwat</p></a>
      <a class='sociallinks' href="https://twitter.com/ChaitanyaShash5" target="_blank"><p><i class="fa fa-twitter-square" aria-hidden="true"></i> Chaitanya Shashwat</p></a>
      </div>
    </div>
    <div class="col-9">
    {% for article in articles %}
    {% if forloop.counter < 4 %}
    <div class="article_block">
    <span title="{{article.title}}">
    <a href="{%url 'articles:detail' slug=article.slug %}">
    <div class="row mt-5">
    <div class="col-6">
        <h2>{{article.title}}</h2>
        <p>{{article.type}}</p>
        <p>By {{article.author}}</p>
        <!-- <p>{{article.date}}</p> -->
        <p>{{article.description}}</p>
      </div>
      <div class="col-1">
        <img src="{{article.thumb.url}}" alt="NO IMAGE FOUND" style="width:300px;height:200px">
      </div>
    </div>
    </a>
    </span>
    </div>
    {% endif %}
    {% endfor %}
    <div class="see_more">
    <div class="row mt-5">
    <div class="col-6">
        <a href="{% url 'articles:articles_home' %}"><h4>See All Articles</h4></a>
      </div>
    </div>
    </div>
  </div>
</div>
  {% endblock %}

templates/join_us.html
{% extends "base.html" %}
{% block body_block%}
<style media="screen">
  p{
    font-size: 1.1em;
  }
</style>
<title>Join Us</title>
<h1 class="mt-5">Join Us</h1>
<hr color="grey">
<h3>We are hiring!</h3>
<p>We are looking for writers who are willing to express their opinions fearlessly. If you have any prior experience, please attach the link to any of your previous works.
  We will revert back as soon as possible.</p>
  <p>For any other queries, get in touch with one of our founders through social media. </p>
<form action="https://submit-form.com/sEJ3AZp9vs-ULNq87RVdJ" target="_self">
  <div class="form-group">
    <label for="formGroupExampleInput">Name</label>
    <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter Name">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <!-- <div class="form-group">
      <label for="formGroupExampleInput">Experience</label>
      <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Please tell us about your experience as a Writer">
  </div> -->
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Experience</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Please tell us about your experience as a Writer"></textarea>
  </div>
  <button type="submit" class="btn btn-primary mb-5">Submit</button>
</form>

{% endblock%}